export { LoginPage } from './t1-auth/a1-login/loginPage';
export type { FormikInitialType } from './t1-auth/a1-login/loginPageType';
export { CheckEmail } from 'pages/t1-auth/a5-checkEmail/checkEmail';
export { ProfilePage } from './t1-auth/a2-profile/profilePage';
export type { updateProfileType } from './t1-auth/a2-profile/profilePageTypes';
export { RecoveryPage } from './t1-auth/a3-recovery/recoveryPage';
export { NewPasswordPage } from './t1-auth/a4-newPassword/newPasswordPage';
export { NotFoundPage } from './t1-auth/a6-notFound/notFoundPage';
export { RegisterPage } from './t1-auth/a0-register/registerPage';
export type { FormikRegisterType } from './t1-auth/a0-register/registerPageTypes';
